[profile.default]
libs = ["lib"]
out = "out"
src = "lib/optimism/packages/contracts-bedrock/src"

remappings = [
  '@openzeppelin/contracts-upgradeable/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts-upgradeable/contracts',
  '@openzeppelin/contracts/=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts/contracts',
  '@rari-capital/solmate/=lib/optimism/packages/contracts-bedrock/lib/solmate',
  '@cwia/=lib/optimism/packages/contracts-bedrock/lib/clones-with-immutable-args/src',
  'forge-std/=lib/optimism/packages/contracts-bedrock/lib/forge-std/src',
  'ds-test/=lib/forge-std/lib/ds-test/src'
]
